<?xml version="1.0"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>Initializer</artifactId>
    <version>1.0.1</version>
    <name>Initializer</name>
    <parent>
        <groupId>io.github.enrik-0</groupId>
        <artifactId>vortex</artifactId>
        <version>1.0.0</version>
    </parent>
    <description>Vortex project initializer</description>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.enrik-0</groupId>
            <artifactId>annotate</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>kik.framework.vortex</groupId>
            <artifactId>http</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.enrik-0</groupId>
            <artifactId>properties</artifactId>
            <version>1.0.1</version>
        </dependency>

        <dependency>
            <groupId>io.github.enrik-0</groupId>
            <artifactId>databaseManager</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.enrik-0</groupId>
            <artifactId>databaseMysql</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>32.0.1-jre</version>
        </dependency>

    </dependencies>
</project>
