# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI on Windows

on:
  push: 
    branches: [ "main" ]
  pull_request:  
    branches: [ "main", "develop", "database-mysql" ]

jobs:
  build:
    runs-on: windows-latest

    services:
      mysql:
        image: mysql:5.7  # You can change the MySQL version if needed
        env:
          MYSQL_ROOT_PASSWORD: 1234  # Change this password as per your requirements
          MYSQL_DATABASE: test  # Change the database name as per your requirements
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MySQL to be ready
      shell: bash
      run: |
        for i in {30..0}; do
          if docker exec ${{ job.services.mysql.id }} mysqladmin ping --silent; then
            break
          fi
          echo 'MySQL is unavailable - sleeping'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo 'MySQL did not become ready in time'
          exit 1
        fi

    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Test with Maven
      run: mvn install
