name: Java CI on Windows

on:
  push: 
    branches: [ "main", "database-mysql"]
  pull_request:  
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MySQL on Windows
      run: |
        choco install mysql --version=5.7.21
        net start mysql

    - name: Configure MySQL
      run: |
        mysqladmin -u root password '1234'
        mysql -u root -p1234 -e "CREATE DATABASE test;"

    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be ready
      shell: bash
      run: |
        for i in {30..0}; do
          if mysqladmin ping --host=127.0.0.1 --user=root --password=1234 --silent; then
            break
          fi
          echo 'MySQL is unavailable - sleeping'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo 'MySQL did not become ready in time'
          exit 1
        fi

    - name: Test with Maven
      run: mvn install
