name: Java CI on Windows

on:
  push: 
    branches: [ "main", "database-mysql"]
  pull_request:  
    branches: [ "main", "develop", "database-mysql" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install MySQL on Windows
      run: |
        choco install mysql

    - name: Start MySQL service
      run: |
        if ((Get-Service mysql).Status -ne 'Running') {
          Start-Service mysql
        }

    - name: Configure MySQL
      run: |
        "C:\tools\mysql\current\bin\mysqladmin.exe" --username root --password '1234'
        "C:\tools\mysql\current\bin\mysql.exe" -u root -p1234 -e "CREATE DATABASE test;"

    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be ready
      shell: bash
      run: |
        for i in {30..0}; do
          if "C:\tools\mysql\current\bin\mysqladmin.exe" ping --host=127.0.0.1 --user=root --password=1234 --silent; then
            break
          fi
          echo 'MySQL is unavailable - sleeping'
          sleep 1
        done
        if [ "$i" = 0 ]; then
          echo 'MySQL did not become ready in time'
          exit 1
        fi

    - name: Test with Maven
      run: mvn install
